# load packages

```{r}
library(tidyverse)
library(ggplot2)
library(ggpubr)
```

# load data

## Daily rainfall_daily data

```{r}
rainfall_daily <- read_csv("D:/Onedrive/PhD_Undernutrition_Uganda_Physical_Accessbility/2_Study_2_Flooding_Analysis/Data/RAW/Rainfall_estimation/Daily_1979_2020/10_4231_6YK1-CQ13/Uganda/entebbe_climate_cfsr.csv")
```

# Process data

```{r}
# Add variable labels
rainfall_daily <- rainfall_daily %>%
    rename(
        date = date,
        prcpmm = prcpmm,
        tmin_c = tmin_c,
        tmax_c = tmax_c
    )

## Convert date to date format
rainfall_daily$date  <- as.Date(rainfall_daily$date, format = "%Y-%m-%d")
```

# Plot Daily data

```{r}
# Plot
p1_daily = ggplot(rainfall_daily, aes(x = date, y = prcpmm, color = prcpmm)) +
    geom_hline(yintercept = c(20, 40, 60, 80, 100, 120, 140 , 160), linetype = "dashed", color = "black", linewidth = 1) +
    geom_line() +
    scale_color_gradient(low = "light blue", high = "red", limits = c(0, 160)) +
    labs(
        title = "Daily Rainfall in mm in Entebbe, Uganda 1979-2020",
        x = "Date",
        y = "Daily Rainfall (mm)"
    ) +
    scale_y_continuous(breaks = seq(0, 160, 20)) +
    theme_bw() +
    theme(
        plot.title = element_text(size = 14, face = "bold"),
        axis.title = element_text(size = 12),
        axis.text = element_text(size = 10),
        legend.title = element_blank(),
        legend.text = element_text(size = 10),
        panel.grid.major = element_blank(),
        panel.grid.minor = element_blank(),
        panel.border = element_blank(),
        panel.background = element_blank()
    )

# Create table with counts of rainfall_daily days above specified thresholds
rainfall_daily$rainfall_category <- cut(rainfall_daily$prcpmm, breaks = c(0, 20, 40, 60, 80, 100, 120, Inf), labels = c("0-20", "20-40", "40-60", "60-80", "80-100", "100-120", "120+"))

p2_daily = table(rainfall_daily$rainfall_category)

p2_daily = ggtexttable(data.frame(p2_daily), cols = c("Daily Rainfall in mm category", "Count"))

# Combine plot and table
plot_daily <- ggarrange(p1_daily, p2_daily,
ncol = 1, nrow = 2,
heights = c(10,3))

plot_daily

# Save plot
ggsave("D:/Onedrive/PhD_Undernutrition_Uganda_Physical_Accessbility/2_Study_2_Flooding_Analysis/Plots/Rainfall_Entebbe_daily.png", plot_daily, width = 10, height = 10, units = "in", dpi = 600)
```

## Hourly rainfall data
```{r}
# load the data
hourly_rain <- read.csv("D:/Onedrive/PhD_Undernutrition_Uganda_Physical_Accessbility/2_Study_2_Flooding_Analysis/Data/RAW/Rainfall_estimation/Hourly_kamp/data/shear_rain.csv")

# Create a variable with the station with the highest hourly_rain and lowest hourly_rain
hourly_rain$Max_1hr_rainfall <- apply(hourly_rain[, c("ACTogether.HQ", "Makerere", "MengoSS", "RC.ClimateCentre", "RC.Warehouse")], 1, max)
hourly_rain$Min_rainfall <- apply(hourly_rain[, c("ACTogether.HQ", "Makerere", "MengoSS", "RC.ClimateCentre", "RC.Warehouse")], 1, min)

# set X as a time variable
hourly_rain$X <- as.POSIXct(hourly_rain$X, format = "%Y-%m-%d %H:%M:%S")

# Plot the differences between the highest and lowest hourly_rain
ggplot(hourly_rain, aes(x = X, y = Max_1hr_rainfall - Min_rainfall, color = Max_1hr_rainfall - Min_rainfall, group = 1)) +
    geom_line() +
    labs(title = "Difference between the highest and lowest hourly_rain in Kampala (April 2019 - March 2020)", x = "Time", y = "Difference in hourly_rain (mm)") +
    theme_bw() +
    theme(plot.title = element_text(size = 14, face = "bold"),
        axis.title = element_text(size = 12),
        axis.text = element_text(size = 10),
        panel.grid.major = element_blank(),
        panel.grid.minor = element_blank(),
        panel.border = element_blank()) +
    scale_color_gradient(low = "lightblue", high = "red")

# Create a line plot of the Max hourly_rain with color based on intensity
p1 = ggplot(hourly_rain, aes(x = X, y = Max_1hr_rainfall, color = Max_1hr_rainfall)) +
    geom_hline(yintercept = seq(20, 160, by = 20), linetype = "dashed", color = "gray", linewidth = 1) +
    geom_line() +
    labs(title = "1-Hourly Rainfall in Kampala (April 2019 - March 2020)", x = "Time", y = "Max rainfall 1hr (mm)") +
    theme_bw() +
    theme(plot.title = element_text(size = 14, face = "bold"),
        axis.title = element_text(size = 12),
        axis.text = element_text(size = 10),
        panel.grid.major = element_blank(),
        panel.grid.minor = element_blank(),
        panel.border = element_blank()) +
    scale_y_continuous(breaks = seq(0, 160, by = 20)) +
    scale_color_gradient(low = "lightblue", high = "red", limits = c(0, 160), name = "1-Hourly Rainfall in mm")

# Create a table that shows the Max_1hr_rainfall hourly_rain per category (0-20, 20-40, 40-60, 60-80, 80-100, 100+)
## Create a new variable that categorizes the Max_1hr_rainfall hourly_rain
hourly_rain$Rainfall_category <- cut(hourly_rain$Max_1hr_rainfall, breaks = c(0, 20, 40, 60, 80, 100, Inf), labels = c("0-20", "20-40", "40-60", "60-80", "80-100", "100+"))

# Create a table that shows the Max_1hr_rainfall hourly_rain per category
p2 <- table(hourly_rain$Rainfall_category)

p2 <- ggtexttable(data.frame(p2), cols = c("1-Hourly Rainfall in mm Category", "Count"))

# Combine the plot and the table
ggarrange(p1, p2, ncol = 1, nrow = 2, heights = c(10, 3))
```

### Create 3-hour and 6-hour totals 
#### Create 3-hour totals
```{r}
# Create 3-hour totals
hourly_rain$three_hour_totals <- hourly_rain$Max_1hr_rainfall + dplyr::lag(hourly_rain$Max_1hr_rainfall, n = 1, default = 0) + dplyr::lag(hourly_rain$Max_1hr_rainfall, n = 2, default = 0)

# Create a line plot of the 3-hour totals with color based on intensity
p3 = ggplot(hourly_rain, aes(x = X, y = three_hour_totals, color = three_hour_totals)) +
    geom_hline(yintercept = seq(20, 160, by = 20), linetype = "dashed", color = "gray", linewidth = 1) +
    geom_line() +
    labs(title = "3-Hourly Totals in Kampala (April 2019 - March 2020)", x = "Time", y = "3-Hour Hourly Max_1hr_rainfall (mm)") +
    theme_bw() +
    theme(plot.title = element_text(size = 14, face = "bold"),
        axis.title = element_text(size = 12),
        axis.text = element_text(size = 10),
        panel.grid.major = element_blank(),
        panel.grid.minor = element_blank(),
        panel.border = element_blank()) +
    scale_y_continuous(breaks = seq(0, 160, by = 20)) +
    scale_color_gradient(low = "lightblue", high = "red", limits = c(0, 160), name = "3-Hourly Rainfall in mm")

# Create a table that shows the 3-hourly Max_1hr_rainfall hourly_rain per category (0-20, 20-40, 40-60, 60-80, 80-100, 100+)
# Create a new variable that categorizes the 3-hourly Max_1hr_rainfall hourly_rain
hourly_rain$Three_hour_category <- cut(hourly_rain$three_hour_totals, breaks = c(0, 20, 40, 60, 80, 100, Inf), labels = c("0-20", "20-40", "40-60", "60-80", "80-100", "100+"))

# Create a table that shows the 3-hourly Max_1hr_rainfall hourly_rain per category
p4 <- table(hourly_rain$Three_hour_category)

p4 <- ggtexttable(data.frame(p4), cols = c("3-Hourly Rainfall in mm Category", "Count"))

# Combine the plot and the table
ggarrange(p3, p4, ncol = 1, nrow = 2, heights = c(10, 3))
```

#### Create 6-hour totals
```{r}
# Create 6-hour totals
hourly_rain$six_hour_totals <- hourly_rain$Max_1hr_rainfall + dplyr::lag(hourly_rain$Max_1hr_rainfall, n = 1, default = 0) + dplyr::lag(hourly_rain$Max_1hr_rainfall, n = 2, default = 0) + dplyr::lag(hourly_rain$Max_1hr_rainfall, n = 3, default = 0) + dplyr::lag(hourly_rain$Max_1hr_rainfall, n = 4, default = 0) + dplyr::lag(hourly_rain$Max_1hr_rainfall, n = 5, default = 0)

# Create a line plot of the 6-hour totals with color based on intensity
p5 = ggplot(hourly_rain, aes(x = X, y = six_hour_totals, color = six_hour_totals)) +
    geom_hline(yintercept = seq(20, 160, by = 20), linetype = "dashed", color = "gray", linewidth = 1) +
    geom_line() +
    labs(title = "6-Hourly Rainfall Totals in Kampala (April 2019 - March 2020)", x = "Time", y = "6-Hour Hourly Max Rainfall (mm)") +
    theme_bw() +
    theme(plot.title = element_text(size = 14, face = "bold"),
        axis.title = element_text(size = 12),
        axis.text = element_text(size = 10),
        panel.grid.major = element_blank(),
        panel.grid.minor = element_blank(),
        panel.border = element_blank()) +
    scale_y_continuous(breaks = seq(0, 160, by = 20)) +
    scale_color_gradient(low = "lightblue", high = "red", limits = c(0, 160), name = "6-Hourly Rainfall in mm")

# Create a table that shows the 6-hourly Max_1hr_rainfall hourly_rain per category (1-6, 2-7, 3-8, etc.)
# Create a new variable that categorizes the 6-hourly Max_1hr_rainfall hourly_rain
hourly_rain$Six_hour_category <- cut(hourly_rain$six_hour_totals, breaks = c(0, 20, 40, 60, 80, 100, Inf), labels = c("0-20", "20-40", "40-60", "60-80", "80-100", "100+"))

# Create a table that shows the 6-hourly Max_1hr_rainfall hourly_rain per category
p6 <- table(hourly_rain$Six_hour_category)

p6 <- ggtexttable(data.frame(p6), cols = c("6 Hourly Rainfall in mm Category", "Count"))

# Combine the plot and the table
ggarrange(p5, p6, ncol = 1, nrow = 2, heights = c(10, 3))
```

#### Combine all hourly plots and tables
```{r}
# Combine the 1-hour, 3-hour, and 6-hour plots and tables
rainfall_hourly_plots = ggarrange(p1, p3, p5, ncol = 1, nrow = 3, widths = 5, heights = 10)
rainfall_hourly_tables = ggarrange(p2, p4, p6, ncol = 1, nrow = 3, widths = 5, heights = 10)

rainfall_hourly_plots
rainfall_hourly_tables

# Save the plot
ggsave("D:/Onedrive/PhD_Undernutrition_Uganda_Physical_Accessbility/2_Study_2_Flooding_Analysis/Plots/Rainfall_Kampala_hourly_plots.png", rainfall_hourly_plots, width = 10, height = 20, units = "in", dpi = 600)

ggsave("D:/Onedrive/PhD_Undernutrition_Uganda_Physical_Accessbility/2_Study_2_Flooding_Analysis/Plots/Rainfall_Kampala_hourly_tables.png", rainfall_hourly_tables, width = 10, height = 20, units = "in", dpi = 600)
```
