# Load packages

```{r}
# Set up renv for package management
if (!requireNamespace("renv", quietly = TRUE)) {
    install.packages("renv")
} else {
    message("renv is already installed.")
}

# Load the renv package
library(renv)

# Check if renv is already active, activate if not
if (!renv::status()$synchronized) {
    renv::activate()
}

# To restore the environment (for a collaborator)
renv::restore()

# Load packages
library(sf)
library(dplyr)
library(foreach)
library(snow)
library(terra)
library(raster)
library(ggplot2)
library(gridExtra)
library(tidyterra)
library(cowplot)
library(viridis)
library(here)
```

# Load pop_impacted all facilities
```{r}
# Load baseline scenario with no flood
baseline_all

# Define the base directory for Flood_all
base_dir <- here("AccessMod/Output/Flood_all")

# Recursively search for all CSV files in the zonalStat folders
pop_coverage_all_files <- list.files(
  path = base_dir,
  pattern = "*.csv",
  full.names = TRUE,
  recursive = TRUE
)

# Filter files to include only those within zonalStat folders
pop_coverage_all_files <- pop_coverage_all_files[grepl("zonalStat", pop_coverage_all_files)]

# Read all CSV files into a list
pop_coverage_all <- lapply(pop_coverage_all_files, read.csv)

# Name each element in the list based on the folder structure and add _all to each name
names(pop_coverage_all) <- paste0(
    gsub(
        pattern = "zonalStat__|\\.csv", 
        replacement = "", 
        x = basename(pop_coverage_all_files)
    ), 
    "_all"
)

# Convert columns to factors for all MLC dataframes
for (name in names(pop_coverage_all)) {
    if (grepl("MLC", name)) {
        pop_coverage_all[[name]]$table.pname2016 <- as.factor(pop_coverage_all[[name]]$table.pname2016)
        pop_coverage_all[[name]]$table.time_m <- as.factor(pop_coverage_all[[name]]$table.time_m)
    }
}

# Load each as a seperate dataframe object
for (i in 1:length(pop_coverage_all)) {
    assign(
        x = names(pop_coverage_all)[i],
        value = pop_coverage_all[[i]]
    )
}

# Remove redundant objects from the global environment
rm(base_dir, pop_coverage_all_files, i, name)
```

# Pre-process data all facilities
```{r}
# Difference flood scenarios with baseline scenarios
pop_coverage_all_diff <- list()

# Loop through each scenario
for (name in names(pop_coverage_all)) {
    # Extract the baseline scenario
    baseline <- pop_coverage_all[[name]]
    
    # Extract the flood scenario
    flood <- pop_coverage_all[[paste0(gsub("_all", "", name), "_flood")]]
    
    # Merge the two dataframes
    diff <- merge(
        x = baseline,
        y = flood,
        by = c("table.pname2016", "table.time_m"),
        suffixes = c("_baseline", "_flood")
    )
    
    # Calculate the difference in population coverage
    diff$table.popCoveredPercent_diff <- diff$table.popCoveredPercent_flood - diff$table.popCoveredPercent_baseline
    
    # Store the difference dataframe in the list
    pop_coverage_all_diff[[name]] <- diff
}
```

# Load pop_impacted hospitals only
```{r}
# Load baseline scenario with no flood
baseline_flood

# Define the base directory for Flood_hosp
base_dir <- here("AccessMod/Output/Flood_hosp")

# Recursively search for all CSV files in the zonalStat folders
pop_coverage_hosp_files <- list.files(
    path = base_dir,
    pattern = "*.csv",
    full.names = TRUE,
    recursive = TRUE
)

# Filter files to include only those within zonalStat folders
pop_coverage_hosp_files <- pop_coverage_hosp_files[grepl("zonalStat", pop_coverage_hosp_files)]

# Read all CSV files into a list
pop_coverage_hosp <- lapply(pop_coverage_hosp_files, read.csv)

# Name each element in the list based on the folder structure and add _hosp to each name
names(pop_coverage_hosp) <- paste0(
        gsub(
                pattern = "zonalStat__|\\.csv", 
                replacement = "", 
                x = basename(pop_coverage_hosp_files)
        ), 
        "_hosp"
)

# Convert columns to factors for all MLC dataframes
for (name in names(pop_coverage_hosp)) {
        if (grepl("MLC", name)) {
                pop_coverage_hosp[[name]]$table.pname2016 <- as.factor(pop_coverage_hosp[[name]]$table.pname2016)
                pop_coverage_hosp[[name]]$table.time_m <- as.factor(pop_coverage_hosp[[name]]$table.time_m)
        }
}

# Load each as a separate dataframe object
for (i in 1:length(pop_coverage_hosp)) {
        assign(
                x = names(pop_coverage_hosp)[i],
                value = pop_coverage_hosp[[i]]
        )
}

# Remove redundant objects from the global environment
rm(base_dir, pop_coverage_hosp_files, i, name)
```

# Pre-process data hospitals only scenario
```{r}
# Plot
ggplot(MLC_100_3600_hosp, aes(x = table.time_m, y = table.popCoveredPercent, fill = table.popCoveredPercent)) +
    geom_bar(stat = "identity") +
    labs(title = "Population Coverage by Time (100mm / 1hr)", x = "Time (minutes)", y = "Population Covered (%)") +
    theme_bw() +
    theme(
        plot.title = element_text(size = 14, face = "bold"),
        axis.title = element_text(size = 12),
        axis.text = element_text(size = 10),
        panel.grid.major = element_blank(),
        panel.grid.minor = element_blank(),
        panel.border = element_blank(),
        legend.position = "none"
    ) +
    facet_wrap(~table.pname2016) +
    scale_fill_gradient(low = "red", high = "light green") +
    theme(plot.margin = margin(1, 1, 1, 1, "cm")) +
    theme(plot.background = element_rect(fill = "white"))
```