#Load libraries
```{r}
# Set up renv for package management
if (!requireNamespace("renv", quietly = TRUE)) {
    install.packages("renv")
} else {
    message("renv is already installed.")
}

# Load the renv package
library(renv)

# Check if renv is already active, activate if not
if (!renv::status()$synchronized) {
    renv::activate()
}

# To restore the environment (for a collaborator)
renv::restore()

# Load libraries
library(sf)
library(dplyr)
library(foreach)
library(snow)
library(terra)
library(raster)
library(ggplot2)
library(gridExtra)
library(tidyterra)
library(cowplot)
library(viridis)
```

# ALL SCENARIOS
## Flood scenarios Travel Time All
```{r}
# Load all .img files in the specified folder
file_path <- "C:/Users/rikib/OneDrive/PhD_Undernutrition_Uganda_Physical_Accessbility/2_Study_2_Flooding_Analysis/AM5_flood_project/out/2024-03-26-15-29-29/All"
file_list <- list.files(file_path, pattern = "\\.img$", full.names = TRUE)

# Load all rasters
raster_list <- lapply(file_list, rast)

# Label the raster files with the corresponding file names
names(raster_list) <- file_list

# load all rasters as separate objects
flood_tt_all_100_10800 <- raster_list[[1]]
flood_tt_all_100_21600 <- raster_list[[2]]
flood_tt_all_100_3600 <- raster_list[[3]]

flood_tt_all_20_10800 <- raster_list[[4]]
flood_tt_all_20_21600 <- raster_list[[5]]
flood_tt_all_20_3600 <- raster_list[[6]]

flood_tt_all_40_10800 <- raster_list[[7]]
flood_tt_all_40_21600 <- raster_list[[8]]
flood_tt_all_40_3600 <- raster_list[[9]]

flood_tt_all_60_10800 <- raster_list[[10]]
flood_tt_all_60_21600 <- raster_list[[11]]
flood_tt_all_60_3600 <- raster_list[[12]]

flood_tt_all_80_10800 <- raster_list[[13]]
flood_tt_all_80_21600 <- raster_list[[14]]
flood_tt_all_80_3600 <- raster_list[[15]]

x <- c(flood_tt_all_20_3600, flood_tt_all_20_10800, flood_tt_all_20_21600, flood_tt_all_40_3600, flood_tt_all_40_10800, flood_tt_all_40_21600, flood_tt_all_60_3600, flood_tt_all_60_10800, flood_tt_all_60_21600, flood_tt_all_80_3600, flood_tt_all_80_10800, flood_tt_all_80_21600, flood_tt_all_100_3600, flood_tt_all_100_10800, flood_tt_all_100_21600)

names(x) <- c("20mm / 1hr", "20mm / 3hr", "20mm / 6hr", "40mm / 1hr", "40mm / 3hr", "40mm / 6hr", "60mm / 1hr", "60mm / 3hr", "60mm / 6hr", "80mm / 1hr", "80mm / 3hr", "80mm / 6hr", "100mm / 1hr", "100mm / 3hr", "100mm x 6hr")

# Create a grid of the plots
gridplot <- panel(x,
    col = data.frame(
        from = c(0, 15, 30, 45, 60, 90, 120, 180),
        to = c(15, 30, 45, 60, 90, 120, 180, Inf),
        color = rev(colorRampPalette(cividis(8))(8))
    ),
    nr = 5, nc = 3,
    axes = FALSE
)

# save the gridplot as a pdf
png("D:/Onedrive/PhD_Undernutrition_Uganda_Physical_Accessbility/2_Study_2_Flooding_Analysis/Plots/flood_tt_all__scenarios.png", width = 40, height = 60, units = "cm", res = 1000)
print(gridplot)
dev.off()
```

## Travel time delta all
```{r}
# Load base travel time raster
base_tt_all <- rast("C:/Users/rikib/OneDrive/PhD_Undernutrition_Uganda_Physical_Accessbility/2_Study_2_Flooding_Analysis/Data/AM5_export/am5_MLC_base_2024_03_19@10_34/raster_travel_time_MLC_base_all/raster_travel_time_MLC_base_all.img")

# Plot the SpatRaster with no axis labels or tick marks, but with a box
base_tt_all %>%
    plot(
        col = colorRampPalette(turbo(8))(8),  # Using turbo for stronger contrast
        breaks = c(0, 15, 30, 45, 60, 90, 120, 180, Inf),  # Define travel time breaks
        nr = 5, nc = 3,  # Grid layout (5 rows, 3 columns)
        axes = FALSE,  # Remove axes and labels
        box = TRUE,  # Keep the plot box
        main = "Baseline Healthcare Accessibility in Travel Time (minutes)",  # Improved title
        legend = FALSE,
        cex.main = 1.5,  # Adjust title font size
    ) %>%
    { grid(nx = NULL, ny = NULL, col = "lightgray", lty = "dashed", lwd = 0.5) } %>%
    {
        legend(
            x = "bottomleft",  # Reposition legend to bottom left
            inset = c(0.12, 0.02),  # Slight inset to avoid clipping
            legend = c( "0-15 min", "15-30 min", "30-45 min", "45-60 min", 
                        "60-90 min", "90-120 min", "120-180 min", ">180 min"),  # Custom travel time labels
            fill = colorRampPalette(viridis::turbo(8))(8),  # Matching the turbo color ramp
            bg = "white",  # Set white background for legend
            cex = 1.4,  # Adjust text size in the legend
            x.intersp = 0.6,  # Reduce horizontal space in the legend
            title = "Travel Time Categories (walking)",  # Improved legend title
            ncol = 2
        )
    } 

# Create delta travel time rasters
delta_tt_all_20_3600 <- base_tt_all - flood_tt_all_20_3600
delta_tt_all_20_10800 <- base_tt_all - flood_tt_all_20_10800
delta_tt_all_20_21600 <- base_tt_all - flood_tt_all_20_21600

delta_tt_all_40_3600 <- base_tt_all - flood_tt_all_40_3600
delta_tt_all_40_10800 <- base_tt_all - flood_tt_all_40_10800
delta_tt_all_40_21600 <- base_tt_all - flood_tt_all_40_21600

delta_tt_all_60_3600 <- base_tt_all - flood_tt_all_60_3600
delta_tt_all_60_10800 <- base_tt_all - flood_tt_all_60_10800
delta_tt_all_60_21600 <- base_tt_all - flood_tt_all_60_21600

delta_tt_all_80_3600 <- base_tt_all - flood_tt_all_80_3600
delta_tt_all_80_10800 <- base_tt_all - flood_tt_all_80_10800
delta_tt_all_80_21600 <- base_tt_all - flood_tt_all_80_21600

delta_tt_all_100_3600 <- base_tt_all - flood_tt_all_100_3600
delta_tt_all_100_10800 <- base_tt_all - flood_tt_all_100_10800
delta_tt_all_100_21600 <- base_tt_all - flood_tt_all_100_21600

x <- c(delta_tt_all_20_3600, delta_tt_all_20_10800, delta_tt_all_20_21600, delta_tt_all_40_3600, delta_tt_all_40_10800, delta_tt_all_40_21600, delta_tt_all_60_3600, delta_tt_all_60_10800, delta_tt_all_60_21600, delta_tt_all_80_3600, delta_tt_all_80_10800, delta_tt_all_80_21600, delta_tt_all_100_3600, delta_tt_all_100_10800, delta_tt_all_100_21600)

names(x) <- c("20mm / 1hr", "20mm / 3hr", "20mm / 6hr", "40mm / 1hr", "40mm / 3hr", "40mm / 6hr", "60mm / 1hr", "60mm / 3hr", "60mm / 6hr", "80mm / 1hr", "80mm / 3hr", "80mm / 6hr", "100mm / 1hr", "100mm / 3hr", "100mm x 6hr")

# Create a grid of the plots
gridplot_delta_tt <- panel(x,
    col = data.frame(
        from = c(-Inf, -180, -120, -90, -60, -45, -30, -15, -0.01),  # Negative time differences
        to = c(-180, -120, -90, -60, -45, -30, -15, -1, 0),          # Matching the color breaks
        color = rev(colorRampPalette(turbo(9))(9))                   # Matching the turbo color palette
    ),
    nr = 5, nc = 3,            # Define number of rows and columns
    axes = FALSE,              # Hide the axes for a cleaner grid
    box = TRUE,                # Add box around each plot for clarity
    grid = TRUE,               # Draw gridlines to distinguish between plots
)

# Plot using ggplot2's autoplot() method from tidyterra
autoplot(x, nrow = 5, ncol = 3) +
  scale_fill_stepsn(
    colours = rev(viridisLite::turbo(8)),  # Matching the turbo color palette with 8 steps
    name = "Delta Travel Time Categories (walking)",  # Improved legend title
    breaks = c(-180, -120, -90, -60, -45, -30, -15, 0),  # Custom breaks
    labels = c(">-180 min", "-120-180 min", "-90-120 min", "-60-90 min", 
               "-45-60 min", "-30-45 min", "-15-30 min", "-0-15 min"),  # Custom legend labels
    na.value = "transparent"  # Hide NAs by making them transparent
  ) +
  theme_minimal() +
  theme(
    legend.position = "bottom",  # Move the legend to the bottom
    legend.title = element_text(size = 12),  # Increase legend title font size
    legend.text = element_text(size = 10),  # Increase legend label font size
    legend.key.width = unit(1.5, "cm"),  # Adjust width of legend keys
    legend.key.height = unit(0.5, "cm"),  # Adjust height of legend keys
    legend.spacing.x = unit(1.5, 'cm'),  # Increase spacing between legend items to avoid overlap
    axis.text = element_blank(),  # Remove axis text
    axis.title = element_blank(),  # Remove axis titles
    panel.grid.major = element_line(color = "gray80", size = 0.5),  # Add major gridlines
    panel.grid.minor = element_line(color = "gray90", size = 0.25),  # Add minor gridlines
    strip.background = element_rect(fill = "white")  # Add white background to facet labels
    ) +
    guides(
    fill = guide_legend(title.position = "top", nrow = 3, byrow = FALSE),  # Move legend title to top and arrange items
    ) +
  ggtitle("Delta Travel Time Accessibility Analysis")


# save the gridplot as a png
png("D:/Onedrive/PhD_Undernutrition_Uganda_Physical_Accessbility/2_Study_2_Flooding_Analysis/Plots/delta_tt_all_scenarios.png", width = 40, height = 60, units = "cm", res = 1000)
print(gridplot_delta_tt)
dev.off()
```

# Hospitals only scenarios
## Flood scenarios Travel Time Hospitals only
```{r}
# Load all .img files in the specified folder
file_path <- "C:/Users/Rik/Onedrive/PhD_Undernutrition_Uganda_Physical_Accessbility/2_Study_2_Flooding_Analysis/AM5_flood_project/out/2024-05-07-10-59-39/All"
file_list <- list.files(file_path, pattern = "\\.img$", full.names = TRUE)

# Load all rasters
raster_list <- lapply(file_list, rast)

# Label the raster files with the corresponding file names
names(raster_list) <- file_list

# load all rasters as separate objects
flood_tt_hosp_100_10800 <- raster_list[[1]]
flood_tt_hosp_100_21600 <- raster_list[[2]]
flood_tt_hosp_100_3600 <- raster_list[[3]]

flood_tt_hosp_20_10800 <- raster_list[[4]]
flood_tt_hosp_20_21600 <- raster_list[[5]]
flood_tt_hosp_20_3600 <- raster_list[[6]]

flood_tt_hosp_40_10800 <- raster_list[[7]]
flood_tt_hosp_40_21600 <- raster_list[[8]]
flood_tt_hosp_40_3600 <- raster_list[[9]]

flood_tt_hosp_60_10800 <- raster_list[[10]]
flood_tt_hosp_60_21600 <- raster_list[[11]]
flood_tt_hosp_60_3600 <- raster_list[[12]]

flood_tt_hosp_80_10800 <- raster_list[[13]]
flood_tt_hosp_80_21600 <- raster_list[[14]]
flood_tt_hosp_80_3600 <- raster_list[[15]]

x_hosp <- c(flood_tt_hosp_20_3600, flood_tt_hosp_20_10800, flood_tt_hosp_20_21600, flood_tt_hosp_40_3600, flood_tt_hosp_40_10800, flood_tt_hosp_40_21600, flood_tt_hosp_60_3600, flood_tt_hosp_60_10800, flood_tt_hosp_60_21600, flood_tt_hosp_80_3600, flood_tt_hosp_80_10800, flood_tt_hosp_80_21600, flood_tt_hosp_100_3600, flood_tt_hosp_100_10800, flood_tt_hosp_100_21600)

names(x_hosp) <- c("20mm / 1hr", "20mm / 3hr", "20mm / 6hr", "40mm / 1hr", "40mm / 3hr", "40mm / 6hr", "60mm / 1hr", "60mm / 3hr", "60mm / 6hr", "80mm / 1hr", "80mm / 3hr", "80mm / 6hr", "100mm / 1hr", "100mm / 3hr", "100mm x 6hr")

# Create a grid of the plots
gridplot_hosp <- panel(x_hosp,
    col = data.frame(
        from = c(0, 15, 30, 45, 60, 90, 120, 180),
        to = c(15, 30, 45, 60, 90, 120, 180, Inf),
        color = rev(colorRampPalette(cividis(8))(8))
    ),
    nr = 5, nc = 3,
    axes = FALSE
)

# save the gridplot as a pdf
png("D:/Onedrive/PhD_Undernutrition_Uganda_Physical_Accessbility/2_Study_2_Flooding_Analysis/Plots/flood_tt_hosp_scenarios.png", width = 40, height = 60, units = "cm", res = 1000)
print(gridplot_hosp)
dev.off()
```


## Travel time delta Hospitals only
```{r}
# Load base hospital travel time raster
base_tt_hosp <- rast("C:/Users/Rik/Onedrive/PhD_Undernutrition_Uganda_Physical_Accessbility/2_Study_2_Flooding_Analysis/Data/AM5_export/am5_MLC_base_2024_03_19@10_34/raster_travel_time_MLC_base_hosp/raster_travel_time_MLC_base_hosp.img")

# Create delta travel time rasters for hospitals only
delta_tt_hosp_20_3600 <- base_tt_hosp - flood_tt_hosp_20_3600
delta_tt_hosp_20_10800 <- base_tt_hosp - flood_tt_hosp_20_10800
delta_tt_hosp_20_21600 <- base_tt_hosp - flood_tt_hosp_20_21600

delta_tt_hosp_40_3600 <- base_tt_hosp - flood_tt_hosp_40_3600
delta_tt_hosp_40_10800 <- base_tt_hosp - flood_tt_hosp_40_10800
delta_tt_hosp_40_21600 <- base_tt_hosp - flood_tt_hosp_40_21600

delta_tt_hosp_60_3600 <- base_tt_hosp - flood_tt_hosp_60_3600
delta_tt_hosp_60_10800 <- base_tt_hosp - flood_tt_hosp_60_10800
delta_tt_hosp_60_21600 <- base_tt_hosp - flood_tt_hosp_60_21600

delta_tt_hosp_80_3600 <- base_tt_hosp - flood_tt_hosp_80_3600
delta_tt_hosp_80_10800 <- base_tt_hosp - flood_tt_hosp_80_10800
delta_tt_hosp_80_21600 <- base_tt_hosp - flood_tt_hosp_80_21600

delta_tt_hosp_100_3600 <- base_tt_hosp - flood_tt_hosp_100_3600
delta_tt_hosp_100_10800 <- base_tt_hosp - flood_tt_hosp_100_10800
delta_tt_hosp_100_21600 <- base_tt_hosp - flood_tt_hosp_100_21600

x_hosp <- c(delta_tt_hosp_20_3600, delta_tt_hosp_20_10800, delta_tt_hosp_20_21600, delta_tt_hosp_40_3600, delta_tt_hosp_40_10800, delta_tt_hosp_40_21600, delta_tt_hosp_60_3600, delta_tt_hosp_60_10800, delta_tt_hosp_60_21600, delta_tt_hosp_80_3600, delta_tt_hosp_80_10800, delta_tt_hosp_80_21600, delta_tt_hosp_100_3600, delta_tt_hosp_100_10800, delta_tt_hosp_100_21600)

names(x_hosp) <- c("20mm / 1hr", "20mm / 3hr", "20mm / 6hr", "40mm / 1hr", "40mm / 3hr", "40mm / 6hr", "60mm / 1hr", "60mm / 3hr", "60mm / 6hr", "80mm / 1hr", "80mm / 3hr", "80mm / 6hr", "100mm / 1hr", "100mm / 3hr", "100mm x 6hr")

# Create a grid of the plots
gridplot_delta_tt_hosp <- panel(x_hosp,
    col = data.frame(
        from = c(-Inf, -180, -120, -90, -60, -45, -30, -15, -0.01),
        to = c(-180, -120, -90, -60, -45, -30, -15, -1, 0),
        color = rev(colorRampPalette(turbo(9))(9))
    ),
    nr = 5, nc = 3,
    axes = FALSE
)

autoplot(x_hosp)

# save the gridplot as a png
png("D:/Onedrive/PhD_Undernutrition_Uganda_Physical_Accessbility/2_Study_2_Flooding_Analysis/Plots/delta_tt_hosp_scenarios.png", width = 40, height = 60, units = "cm", res = 1000)
print(gridplot_delta_tt_hosp)
dev.off()
```

# Comparison of all scenarios
```{r}
# Create a grid of the plots for all scenarios
gridplot_all <- panel(x,
    col = data.frame(
        from = c(0, 15, 30, 45, 60, 90, 120, 180),
        to = c(15, 30, 45, 60, 90, 120, 180, Inf),
        color = rev(colorRampPalette(cividis(8))(8))
    ),
    nr = 5, nc = 3,
    axes = FALSE
)

# Create a grid of the plots for hospital only scenarios
gridplot_hosp <- panel(x_hosp,
    col = data.frame(
        from = c(0, 15, 30, 45, 60, 90, 120, 180),
        to = c(15, 30, 45, 60, 90, 120, 180, Inf),
        color = rev(colorRampPalette(cividis(8))(8))
    ),
    nr = 5, nc = 3,
    axes = FALSE
)

# Create a grid of the plots for delta travel time in all scenarios
gridplot_delta_all <- panel(x,
    col = data.frame(
        from = c(-Inf, -180, -120, -90, -60, -45, -30, -15, -0.01),
        to = c(-180, -120, -90, -60, -45, -30, -15, -1, 0),
        color = rev(colorRampPalette(turbo(9))(9))
    ),
    nr = 5, nc = 3,
    axes = FALSE
)

# Create a grid of the plots for delta travel time in hospital only scenarios
gridplot_delta_hosp <- panel(x_hosp,
    col = data.frame(
        from = c(-Inf, -180, -120, -90, -60, -45, -30, -15, -0.01),
        to = c(-180, -120, -90, -60, -45, -30, -15, -1, 0),
        color = rev(colorRampPalette(turbo(9))(9))
    ),
    nr = 5, nc = 3,
    axes = FALSE
)

# Create a grid of the plots for comparison between all scenarios and hospital only scenarios
gridplot_comparison <- grid.arrange(gridplot_all, gridplot_hosp, nrow = 2)

# Create a grid of the plots for comparison between delta travel time in all scenarios and hospital only scenarios
gridplot_delta_comparison <- grid.arrange(gridplot_delta_all, gridplot_delta_hosp, nrow = 2)

# save the gridplot comparison as a pdf
pdf("D:/Onedrive/PhD_Undernutrition_Uganda_Physical_Accessbility/2_Study_2_Flooding_Analysis/Plots/comparison_all_hosp_scenarios.pdf", width = 40, height = 60, units = "cm")
print(gridplot_comparison)
dev.off()

# save the gridplot delta comparison as a pdf
pdf("D:/Onedrive/PhD_Undernutrition_Uganda_Physical_Accessbility/2_Study_2_Flooding_Analysis/Plots/comparison_delta_all_hosp_scenarios.pdf", width = 40, height = 60, units = "cm")
print(gridplot_delta_comparison)
dev.off()
```