#Load libraries
```{r}
library(sf)
library(dplyr)
library(foreach)
library(snow)
library(terra)
library(raster)
library(ggplot2)
library(gridExtra)
library(tidyterra)
library(cowplot)
library(viridis)
```

# Flood scenarios Travel Time All
```{r}
# Load all .img files in the specified folder
file_path <- "D:/Onedrive/PhD_Undernutrition_Uganda_Physical_Accessbility/2_Study_2_Flooding_Analysis/AM5_flood_project/out/2024-03-26-15-29-29/All"
file_list <- list.files(file_path, pattern = "\\.img$", full.names = TRUE)

# Load all rasters 
raster_list <- lapply(file_list, rast)

# Label the raster files with the corresponding file names
names(raster_list) <- file_list

# load all rasters as separate objects
flood_tt_all_100_10800 = raster_list[[1]]
flood_tt_all_100_21600 = raster_list[[2]]
flood_tt_all_100_3600 = raster_list[[3]]

flood_tt_all_20_10800 = raster_list[[4]]
flood_tt_all_20_21600 = raster_list[[5]]
flood_tt_all_20_3600 = raster_list[[6]]

flood_tt_all_40_10800 = raster_list[[7]]
flood_tt_all_40_21600 = raster_list[[8]]
flood_tt_all_40_3600 = raster_list[[9]]

flood_tt_all_60_10800 = raster_list[[10]]
flood_tt_all_60_21600 = raster_list[[11]]
flood_tt_all_60_3600 = raster_list[[12]]

flood_tt_all_80_10800 = raster_list[[13]]
flood_tt_all_80_21600 = raster_list[[14]]
flood_tt_all_80_3600 = raster_list[[15]]

x = c(flood_tt_all_20_3600, flood_tt_all_20_10800, flood_tt_all_20_21600, flood_tt_all_40_3600, flood_tt_all_40_10800, flood_tt_all_40_21600, flood_tt_all_60_3600, flood_tt_all_60_10800, flood_tt_all_60_21600, flood_tt_all_80_3600, flood_tt_all_80_10800, flood_tt_all_80_21600, flood_tt_all_100_3600, flood_tt_all_100_10800, flood_tt_all_100_21600)

names(x) <- c("20mm / 1hr", "20mm / 3hr", "20mm / 6hr", "40mm / 1hr", "40mm / 3hr", "40mm / 6hr", "60mm / 1hr", "60mm / 3hr", "60mm / 6hr", "80mm / 1hr", "80mm / 3hr", "80mm / 6hr", "100mm / 1hr", "100mm / 3hr", "100mm x 6hr")

# Create a grid of the plots
gridplot = panel(x, col = data.frame(from = c(0, 15, 30, 45, 60, 90, 120, 180), 
  to = c(15, 30, 45, 60, 90, 120, 180, Inf), 
  color = rev(colorRampPalette(cividis(8))(8))),
  nr = 5, nc = 3,
  axes = FALSE
)

# save the gridplot as a pdf
png("D:/Onedrive/PhD_Undernutrition_Uganda_Physical_Accessbility/2_Study_2_Flooding_Analysis/Plots/flood_tt_all__scenarios.png", width = 40, height = 60, units = "cm", res = 1000)
print(gridplot)
dev.off()
```

## Travel time delta all
```{r}
# Load base travel time raster
base_tt_all = rast("D:/Onedrive/PhD_Undernutrition_Uganda_Physical_Accessbility/2_Study_2_Flooding_Analysis/Data/Travel_time_surfaces/am5_MLC_base_2024_03_19@10_34/raster_travel_time_MLC_base_all/raster_travel_time_MLC_base_all.img")

# Create delta travel time rasters
delta_tt_all_20_3600 = base_tt_all - flood_tt_all_20_3600
delta_tt_all_20_10800 = base_tt_all - flood_tt_all_20_10800
delta_tt_all_20_21600 = base_tt_all - flood_tt_all_20_21600

delta_tt_all_40_3600 = base_tt_all - flood_tt_all_40_3600
delta_tt_all_40_10800 = base_tt_all - flood_tt_all_40_10800
delta_tt_all_40_21600 = base_tt_all - flood_tt_all_40_21600

delta_tt_all_60_3600 = base_tt_all - flood_tt_all_60_3600
delta_tt_all_60_10800 = base_tt_all - flood_tt_all_60_10800
delta_tt_all_60_21600 = base_tt_all - flood_tt_all_60_21600

delta_tt_all_80_3600 = base_tt_all - flood_tt_all_80_3600
delta_tt_all_80_10800 = base_tt_all - flood_tt_all_80_10800
delta_tt_all_80_21600 = base_tt_all - flood_tt_all_80_21600

delta_tt_all_100_3600 = base_tt_all - flood_tt_all_100_3600
delta_tt_all_100_10800 = base_tt_all - flood_tt_all_100_10800
delta_tt_all_100_21600 = base_tt_all - flood_tt_all_100_21600

x = c(delta_tt_all_20_3600, delta_tt_all_20_10800, delta_tt_all_20_21600, delta_tt_all_40_3600, delta_tt_all_40_10800, delta_tt_all_40_21600, delta_tt_all_60_3600, delta_tt_all_60_10800, delta_tt_all_60_21600, delta_tt_all_80_3600, delta_tt_all_80_10800, delta_tt_all_80_21600, delta_tt_all_100_3600, delta_tt_all_100_10800, delta_tt_all_100_21600)

names(x) <- c("20mm / 1hr", "20mm / 3hr", "20mm / 6hr", "40mm / 1hr", "40mm / 3hr", "40mm / 6hr", "60mm / 1hr", "60mm / 3hr", "60mm / 6hr", "80mm / 1hr", "80mm / 3hr", "80mm / 6hr", "100mm / 1hr", "100mm / 3hr", "100mm x 6hr")

# Create a grid of the plots
gridplot_delta_tt = panel(x, col = data.frame(from = c(-Inf, -180, -120, -90, -60, -45, -30, -15, -0.01), 
  to = c(-180, -120, -90, -60, -45, -30, -15, -1, 0), 
  color = rev(colorRampPalette(turbo(9))(9))),
  nr = 5, nc = 3,
  axes = FALSE
)

gridplot_delta_tt

# save the gridplot as a png
png("D:/Onedrive/PhD_Undernutrition_Uganda_Physical_Accessbility/2_Study_2_Flooding_Analysis/Plots/delta_tt_all_scenarios.png", width = 40, height = 60, units = "cm", res = 1000)
print(gridplot_delta_tt)
dev.off()
```

# Flood scenarios Travel Time Hospitals only
```{r}


``