# Analysis of Flood Impact on Population and Development Indicators

## Loading packages

```{r}
# Function to check and install required packages
check_install_packages <- function(packages) {
    # Check if packages are installed
    missing_packages <- packages[!sapply(packages, requireNamespace, quietly = TRUE)]

    # Install missing packages
    if (length(missing_packages) > 0) {
        install.packages(missing_packages, dependencies = TRUE)
    }

    # Load all packages
    lapply(packages, library, character.only = TRUE)
}

# List of required packages
required_packages <- c("terra", "ggplot2", "dplyr", "viridis", "rasterVis", "tidyterra", "patchwork")

# Check and install required packages
check_install_packages(required_packages)

# Load all required packages
lapply(required_packages, library, character.only = TRUE)
```

## Data Loading

```{r}
# {r} code block for loading and handling data
# Set the directory path
folder_path_dev <- "C:/Users/Rik/OneDrive/PhD_Undernutrition_Uganda_Physical_Accessbility/2_Study_2_Flooding_Analysis/Data/RAW/World_Pop_development_indicators/UGA_Maternal_and_child_health"
folder_path_dev1 <- "C:/Users/Rik/OneDrive/PhD_Undernutrition_Uganda_Physical_Accessbility/2_Study_2_Flooding_Analysis/Data/RAW/World_Pop_development_indicators/UGA_Maternal_and_child_socioeconomic"
folder_path_pop <- "C:/Users/Rik/OneDrive/PhD_Undernutrition_Uganda_Physical_Accessbility/2_Study_2_Flooding_Analysis/Data/RAW/WorldPop_density/Inaccessmod"

# List all .tif files in the directory
tif_files_dev <- list.files(path = folder_path_dev, pattern = "\\.tif$", full.names = TRUE)
tif_files_dev1 <- list.files(path = folder_path_dev1, pattern = "\\.tif$", full.names = TRUE)
tif_files_pop <- list.files(path = folder_path_pop, pattern = "\\.tif$", full.names = TRUE)

# Load all raster layers  using the rast function
raster_data_dev <- lapply(tif_files_dev, rast)
raster_data_dev1 <- lapply(tif_files_dev1, rast)
raster_data_population <- lapply(tif_files_pop, rast)

raster_data_all_dev <- c(raster_data_dev, raster_data_dev1)

# Load and handle the administrative boundary of Kampala
kampala_extent <- vect("C:/Users/Rik/Onedrive/PhD_Undernutrition_Uganda_Physical_Accessbility/2_Study_2_Flooding_Analysis/InAccessmod/Uganda/data/vBorders/20240308161055/processed/20240308162043/vBorders_Processed.shp")

# Reproject the vector data to the same projection as the raster data for faster processing
kampala_extent <- project(kampala_extent, crs = crs(raster_data_dev[[1]]), "+proj=longlat +datum=WGS84")


# Load all rasters as separate objects
UGA_ANC_MEAN <- raster_data_all_dev[[1]]
UGA_ANC_SD <- raster_data_all_dev[[2]]
UGA_INSURANCE_MEAN <- raster_data_all_dev[[3]]
UGA_INSURANCE_SD <- raster_data_all_dev[[4]]
UGA_MALNUTRITION_MEAN <- raster_data_all_dev[[5]]
UGA_MALNUTRITION_SD <- raster_data_all_dev[[6]]
UGA_PNC_MEAN <- raster_data_all_dev[[7]]
UGA_PNC_SD <- raster_data_all_dev[[8]]
UGA_SBA_MEAN <- raster_data_all_dev[[9]]
UGA_SBA_SD <- raster_data_all_dev[[10]]
UGA_TT_MEAN <- raster_data_all_dev[[11]]
UGA_TT_SD <- raster_data_all_dev[[12]]
UGA_DECISION_MEAN <- raster_data_all_dev[[13]]
UGA_DECISION_SD <- raster_data_all_dev[[14]]
UGA_HWEALTH_MEAN <- raster_data_all_dev[[15]]
UGA_HWEALTH_SD <- raster_data_all_dev[[16]]
UGA_MEDUCATION_MEAN <- raster_data_all_dev[[17]]
UGA_MEDUCATION_SD <- raster_data_all_dev[[18]]

# Load all population rasters as separate objects
UGA_POPULATION_TOTAL <- raster_data_population[[1]]
UGA_POPULATION_U5 <- raster_data_population[[2]]
UGA_POPULATION_WRA <- raster_data_population[[3]]

# Crop the raster data to the extent of Kampala
UGA_ANC_MEAN <- crop(UGA_ANC_MEAN, kampala_extent)
UGA_ANC_SD <- crop(UGA_ANC_SD, kampala_extent)
UGA_INSURANCE_MEAN <- crop(UGA_INSURANCE_MEAN, kampala_extent)
UGA_INSURANCE_SD <- crop(UGA_INSURANCE_SD, kampala_extent)
UGA_MALNUTRITION_MEAN <- crop(UGA_MALNUTRITION_MEAN, kampala_extent)
UGA_MALNUTRITION_SD <- crop(UGA_MALNUTRITION_SD, kampala_extent)
UGA_PNC_MEAN <- crop(UGA_PNC_MEAN, kampala_extent)
UGA_PNC_SD <- crop(UGA_PNC_SD, kampala_extent)
UGA_SBA_MEAN <- crop(UGA_SBA_MEAN, kampala_extent)
UGA_SBA_SD <- crop(UGA_SBA_SD, kampala_extent)
UGA_TT_MEAN <- crop(UGA_TT_MEAN, kampala_extent)
UGA_TT_SD <- crop(UGA_TT_SD, kampala_extent)
UGA_DECISION_MEAN <- crop(UGA_DECISION_MEAN, kampala_extent)
UGA_DECISION_SD <- crop(UGA_DECISION_SD, kampala_extent)
UGA_HWEALTH_MEAN <- crop(UGA_HWEALTH_MEAN, kampala_extent)
UGA_HWEALTH_SD <- crop(UGA_HWEALTH_SD, kampala_extent)
UGA_MEDUCATION_MEAN <- crop(UGA_MEDUCATION_MEAN, kampala_extent)
UGA_MEDUCATION_SD <- crop(UGA_MEDUCATION_SD, kampala_extent)

UGA_POPULATION_TOTAL <- crop(UGA_POPULATION_TOTAL, kampala_extent)
UGA_POPULATION_U5 <- crop(UGA_POPULATION_U5, kampala_extent)
UGA_POPULATION_WRA <- crop(UGA_POPULATION_WRA, kampala_extent)

# Mask the raster data to the extent of Kampala
UGA_ANC_MEAN <- mask(UGA_ANC_MEAN, kampala_extent)
UGA_ANC_SD <- mask(UGA_ANC_SD, kampala_extent)
UGA_INSURANCE_MEAN <- mask(UGA_INSURANCE_MEAN, kampala_extent)
UGA_INSURANCE_SD <- mask(UGA_INSURANCE_SD, kampala_extent)
UGA_MALNUTRITION_MEAN <- mask(UGA_MALNUTRITION_MEAN, kampala_extent)
UGA_MALNUTRITION_SD <- mask(UGA_MALNUTRITION_SD, kampala_extent)
UGA_PNC_MEAN <- mask(UGA_PNC_MEAN, kampala_extent)
UGA_PNC_SD <- mask(UGA_PNC_SD, kampala_extent)
UGA_SBA_MEAN <- mask(UGA_SBA_MEAN, kampala_extent)
UGA_SBA_SD <- mask(UGA_SBA_SD, kampala_extent)
UGA_TT_MEAN <- mask(UGA_TT_MEAN, kampala_extent)
UGA_TT_SD <- mask(UGA_TT_SD, kampala_extent)
UGA_DECISION_MEAN <- mask(UGA_DECISION_MEAN, kampala_extent)
UGA_DECISION_SD <- mask(UGA_DECISION_SD, kampala_extent)
UGA_HWEALTH_MEAN <- mask(UGA_HWEALTH_MEAN, kampala_extent)
UGA_HWEALTH_SD <- mask(UGA_HWEALTH_SD, kampala_extent)
UGA_MEDUCATION_MEAN <- mask(UGA_MEDUCATION_MEAN, kampala_extent)
UGA_MEDUCATION_SD <- mask(UGA_MEDUCATION_SD, kampala_extent)

UGA_POPULATION_TOTAL <- mask(UGA_POPULATION_TOTAL, kampala_extent)
UGA_POPULATION_U5 <- mask(UGA_POPULATION_U5, kampala_extent)
UGA_POPULATION_WRA <- mask(UGA_POPULATION_WRA, kampala_extent)

# Set the names of the raster layers
names(UGA_ANC_MEAN) <- "ANC - Proportion of children aged 12 to 23 months born to mothers who did not attend antenatal care (Mean)"
names(UGA_ANC_SD) <- "ANC - Proportion of children aged 12 to 23 months born to mothers who did not attend antenatal care (SD)"
names(UGA_INSURANCE_MEAN) <- "Insurance - Proportion of children aged 12 to 23 months who had no health insurance (Mean)"
names(UGA_INSURANCE_SD) <- "Insurance - Proportion of children aged 12 to 23 months who had no health insurance (SD)"
names(UGA_MALNUTRITION_MEAN) <- "Malnutrition - Proportion of children aged 12 to 23 months who were underweight (Mean)"
names(UGA_MALNUTRITION_SD) <- "Malnutrition - Proportion of children aged 12 to 23 months who were underweight (SD)"
names(UGA_PNC_MEAN) <- "PNC - Proportion of children aged 12 to 23 months who did not receive (or recall) post-natal care within 2 months after birth (Mean)"
names(UGA_PNC_SD) <- "PNC - Proportion of children aged 12 to 23 months who did not receive (or recall) post-natal care within 2 months after birth (SD)"
names(UGA_SBA_MEAN) <- "SBA - Proportion of children aged 12 to 23 months who were not delivered by a skilled birth attendant (Mean)"
names(UGA_SBA_SD) <- "SBA - Proportion of children aged 12 to 23 months who were not delivered by a skilled birth attendant (SD)"
names(UGA_TT_MEAN) <- "TT - Proportion of children aged 12 to 23 months who had no tetanus toxoid injections before birth (Mean)"
names(UGA_TT_SD) <- "TT - Proportion of children aged 12 to 23 months who had no tetanus toxoid injections before birth (SD)"
names(UGA_HWEALTH_MEAN) <- "HWEALTH - Proportion of children aged 12 to 23 months born to the poorest / poorer households (Mean)"
names(UGA_HWEALTH_SD) <- "HWEALTH - Proportion of children aged 12 to 23 months born to the poorest / poorer households (SD)"
names(UGA_MEDUCATION_MEAN) <- "MEDUCATION - Proportion of children aged 12 to 23 months born to mothers who had no formal education (Mean)"
names(UGA_MEDUCATION_SD) <- "MEDUCATION - Proportion of children aged 12 to 23 months born to mothers who had no formal education (SD)"
names(UGA_DECISION_MEAN) <- "DECISION - Proportion of women aged 15 to 49 years\n who did not participate in decision-making\n in their households (Mean)"
names(UGA_DECISION_SD) <- "DECISION - Proportion of women aged 15 to 49 years\n who did not participate in decision-making\n in their households (SD)"

names(UGA_POPULATION_TOTAL) <- "Total Population"
names(UGA_POPULATION_U5) <- "Population under 5 years"
names(UGA_POPULATION_WRA) <- "Population Women of Reproductive Age"

# Create a list of the mean and SD rasters
raster_data_mean <- c(UGA_ANC_MEAN, UGA_INSURANCE_MEAN, UGA_MALNUTRITION_MEAN, UGA_PNC_MEAN, UGA_SBA_MEAN, UGA_TT_MEAN, UGA_DECISION_MEAN, UGA_HWEALTH_MEAN, UGA_MEDUCATION_MEAN)
raster_data_sd <- c(UGA_ANC_SD, UGA_INSURANCE_SD, UGA_MALNUTRITION_SD, UGA_PNC_SD, UGA_SBA_SD, UGA_TT_SD, UGA_DECISION_SD, UGA_HWEALTH_SD, UGA_MEDUCATION_SD)
raster_data_all_dev <- c(raster_data_mean, raster_data_sd)

raster_data_pop <- c(UGA_POPULATION_TOTAL, UGA_POPULATION_U5, UGA_POPULATION_WRA)
```

## Plotting

```{r}
# {r} code block for plotting
# Function to create a ggplot for each raster with an individual legend
create_plot <- function(raster_layer, title) {
    # Insert a line break specifically after 'months'
    formatted_title <- gsub("months", "months\n", title, fixed = TRUE)

    p <- gplot(raster_layer) +
        geom_tile(aes(fill = value)) +
        scale_fill_viridis_c(option = "turbo") + # Using Viridis color scale, change as needed
        labs(title = formatted_title, fill = "Value") +
        theme_minimal() +
        theme(
            legend.position = "right", # Adjust legend position as needed
            plot.title = element_text(hjust = 0.5), # Center the title horizontally
            plot.margin = unit(c(1, 1, 1, 1), "lines"),
            plot.background = element_rect(fill = "white"), # Set plot background color to white
            panel.background = element_rect(fill = "white"), # Set panel background color to white
            panel.grid.major = element_blank(), # Remove major grid lines
            panel.grid.minor = element_blank(), # Remove minor grid lines
            axis.line = element_line(color = "black"), # Set axis line color to black
            axis.text = element_text(color = "black"), # Set axis text color to black
            axis.title = element_text(color = "black") # Set axis title color to black
        ) # Adjust margins around the plots
    return(p)
}

# Create a list of plots
plots_mean <- lapply(raster_data_mean, function(x) create_plot(x, names(x)))
plots_sd <- lapply(raster_data_sd, function(x) create_plot(x, names(x)))
plots_all <- lapply(raster_data_all_dev, function(x) create_plot(x, names(x)))

plots_pop <- lapply(raster_data_pop, function(x) create_plot(x, names(x)))

# Use patchwork to combine and arrange all plots
plot_layout_mean <- wrap_plots(plots_mean, ncol = 2) # Adjust the number of columns as needed
plot_layout_sd <- wrap_plots(plots_sd, ncol = 2) # Adjust the number of columns as needed
plot_layout_all <- wrap_plots(plots_all, ncol = 2) # Adjust the number of columns as needed

plot_layout_pop <- wrap_plots(plots_pop, ncol = 2) # Adjust the number of columns as needed

# Print the plot layouts
print(plot_layout_mean)
print(plot_layout_sd)
print(plot_layout_all)

print(plot_layout_pop)
```

## Analysis

```{r}
# {r} code block for analysis
# Function to multiply each mean raster by the total population raster
multiply_by_population <- function(raster_data_mean, population_raster) {
    multiplied_rasters <- lapply(raster_data_mean, function(r) {
        # Multiply the raster values
        result_raster <- r * population_raster
        # Set the name of the new raster to indicate it has been processed
        names(result_raster) <- paste("PopAdjusted", names(r), sep = "_")
        return(result_raster)
    })
    return(multiplied_rasters)
}

# Usage of the function with your data
adjusted_dev_rasters <- multiply_by_population(raster_data_mean, UGA_POPULATION_TOTAL)




```
