# Loading packages

```{r package loading}
library(tidyverse)
library(haven)
library(lattice)
library(data.table)
library(knitr)
library(survey)
 options(survey.lonely.psu="adjust")
library(expss)
library(ggplot2)
library(labelled)
library(table1)
library(readxl)
library(GGally)
library(kableExtra)
library(xtable)
library(modelsummary)
library(performance)
library(finalfit)
library(naniar)
library(rms)
library(openxlsx)
library(rcompanion)
library(questionr)
library(flextable)
library(MASS)
library(car)
library(cowplot)
library(heatmaply)
library(esquisse)
library(visreg)
library(forcats) 
library(mosaic)
library(DT)
library(mice)
library(gtsummary)
library(styler)
library(languageserver)
library(httpgd)
library(plotly)
library(sf)
library(gridExtra)
library(terra)
library(tidyterra)
```

# Data handling

#### Loading data and creating subset

```{r Dota load and subsetting}
# Load the children dataset from a .SAV file 

#depending on computer C:/Users/Rik/OneDrive/PhD_Undernutrition_Uganda_Physical_Accessbility/1_Study_1_Physical_access/Data/DATA/Uganda Full/DHS Clusters/UGKR7BSV_Children/UGKR7BFL.SAV   

DHS_children_sub <- read_sav("D:/Onedrive/PhD_Undernutrition_Uganda_Physical_Accessbility/1_Study_1_Physical_access/Data/DATA/Uganda Full/DHS Clusters/UGKR7BSV_Children/UGKR7BFL.SAV")


# Filter out rows with children who are no longer alive (B5 == 1)
DHS_children_sub = subset(DHS_children_sub, B5 == 1)

# Keep only children with anthropometric measurements (non-missing HW5 values)
DHS_children_sub = DHS_children_sub %>% drop_na(HW5)

Kamp = subset(DHS_children_sub, V024 == 0)

DHS_loc <- st_read("D:/Onedrive/PhD_Undernutrition_Uganda_Physical_Accessbility/1_Study_1_Physical_access/Data/DATA/Uganda Full/DHS Clusters/UGGE7AFL/UGGE7AFL.shp")

# Only select 
DHS_loc <- subset(DHS_loc, ADM1NAME == "KAMPALA")


Kamp <- Kamp %>%
  group_by(V001) %>%
  summarise(Count = n()) %>%
  mutate(V001 = reorder(V001, Count)) # Reorder V001 based on Count

# Rename V001 to DHSCUST
names(Kamp)[names(Kamp) == "V001"] <- "DHSCLUST"

DHS_loc <- merge(DHS_loc, Kamp, by = "DHSCLUST", all.x = TRUE)

# Read the shapefile
parishes <- st_read("D:/Onedrive/PhD_Undernutrition_Uganda_Physical_Accessbility/2_Study_2_Flooding_Analysis/Data/Processed/Adm_boundaries_parishes/Parishes_Kamp_UTM36N.shp")

# Reproject the parishes shapefile to the same projection as the DHS location data
parishes <- st_transform(parishes, st_crs(DHS_loc))

map = ggplot() +
  geom_sf(data = parishes, fill = "lightgray", color = "black") +  # Add the shapefile as a base layer
  geom_point(data = DHS_loc, aes(x = LONGNUM, y = LATNUM, size = Count, color = Count), alpha = 0.7) +
  labs(title = "Distribution of Children per Cluster in Kampala", x = "Longitude", y = "Latitude") +
  scale_color_gradient(low = "blue", high = "red") +
  scale_size(range = c(2, 10), name = "Count") +
  theme_bw() +
  theme(plot.title = element_text(size = 14, face = "bold"),
        axis.title = element_text(size = 12),
        axis.text = element_text(size = 10),
        panel.grid.major = element_blank(),
        panel.grid.minor = element_blank(),
        panel.border = element_blank(),
        legend.position = "right")

# Summary statistics of the count variable
summary(Kamp$Count)

# Create a bar plot of the cluster distribution
ggplot(Kamp, aes(x = DHSCLUST, y = Count)) +
  geom_bar(stat = "identity", fill = "steelblue") + # Use 'identity' to use Count values directly
  labs(title = "Distribution of Clusters in Kampala", x = "Cluster", y = "Count") +
  theme_bw() + # Use a black and white theme
  theme(plot.title = element_text(size = 14, face = "bold"), # Increase title size and make it bold
    axis.title = element_text(size = 12), # Increase axis label size
    axis.text = element_text(size = 10), # Increase axis tick label size
    panel.grid.major = element_blank(), # Remove major grid lines
    panel.grid.minor = element_blank(), # Remove minor grid lines
    panel.border = element_blank(), # Remove plot border
    legend.position = "none") + # Remove legend
  scale_y_continuous(breaks = seq(0, max(Kamp$Count), by = 1)) + # Add more y ticks
  geom_hline(yintercept = seq(0, max(Kamp$Count), by = 1), linetype = "dotted", color = "gray") # Add dotted lines

```

## Idea
```{r}
############################################################################################################
# THIS IS TEST DATA AND NOT REAL DATA
############################################################################################################

df <- data.frame(
  Combination = c("40mm_1hr", "40mm_2hr", "40mm_3hr", "80mm_1hr", "80mm_2hr", "80mm_3hr", "120mm_1hr", "120mm_2hr", "120mm_3hr"),
  Rainfall = c(40, 40, 40, 80, 80, 80, 120, 120, 120),
  Duration = c(1, 2, 3, 1, 2, 3, 1, 2, 3),
  Healthcare_Coverage = c(90, 75, 60, 75, 60, 45, 60, 45, 30)
)

ggplot(df, aes(x = Combination, y = Healthcare_Coverage, fill = factor(Rainfall))) +
  geom_bar(stat = "identity", position = "dodge") +
  geom_line(aes(group = Rainfall), position = position_dodge(width = 0.9), linewidth = 3) +
  labs(title = "Healthcare Coverage by Rainfall and Duration", x = "Combination", y = "Healthcare Coverage") +
  scale_fill_discrete(name = "Rainfall (mm)", labels = c("40mm", "80mm", "120mm")) +
  theme_bw() +
  theme(plot.title = element_text(size = 14, face = "bold"),
    axis.title = element_text(size = 12),
    axis.text = element_text(size = 10),
    panel.grid.major = element_blank(),
    panel.grid.minor = element_blank(),
    panel.border = element_blank(),
    legend.position = "top") + 
      scale_x_discrete(limits = c("40mm_1hr", "40mm_2hr", "40mm_3hr", "80mm_1hr", "80mm_2hr", "80mm_3hr", "120mm_1hr", "120mm_2hr", "120mm_3hr"))


ggplot(df, aes(x = Combination, y = Healthcare_Coverage, fill = factor(Duration))) +
  geom_bar(stat = "identity", position = "dodge") +
  geom_line(aes(group = Duration), position = position_dodge(width = 0.9), linewidth = 3) +
  labs(title = "Healthcare Coverage by Rainfall and Duration", x = "Combination", y = "Healthcare Coverage") +
  scale_fill_discrete(name = "Duration (hours)", labels = c("1 hour", "2 hours", "3 hours")) +
  theme_bw() +
  theme(plot.title = element_text(size = 14, face = "bold"),
    axis.title = element_text(size = 12),
    axis.text = element_text(size = 10),
    panel.grid.major = element_blank(),
    panel.grid.minor = element_blank(),
    panel.border = element_blank(),
    legend.position = "top") +
      scale_x_discrete(limits = c("40mm_1hr", "40mm_2hr", "40mm_3hr", "80mm_1hr", "80mm_2hr", "80mm_3hr", "120mm_1hr", "120mm_2hr", "120mm_3hr"))

      # Line plot of Healthcare Coverage by Rainfall and Duration
      ggplot(df, aes(x = Combination, y = Healthcare_Coverage, group = Rainfall, color = factor(Rainfall))) +
        geom_line() +
        labs(title = "Healthcare Coverage by Rainfall and Duration", x = "Combination", y = "Healthcare Coverage") +
        scale_color_discrete(name = "Rainfall (mm)", labels = c("40mm", "80mm", "120mm")) +
        theme_bw() +
        theme(plot.title = element_text(size = 14, face = "bold"),
              axis.title = element_text(size = 12),
              axis.text = element_text(size = 10),
              panel.grid.major = element_blank(),
              panel.grid.minor = element_blank(),
              panel.border = element_blank()) +
              scale_x_discrete(limits = c("40mm_1hr", "40mm_2hr", "40mm_3hr", "80mm_1hr", "80mm_2hr", "80mm_3hr", "120mm_1hr", "120mm_2hr", "120mm_3hr"))
```

# Flood shapefiles
```{r}
# Read the shapefiles
# Load all flood_extents from subfolders
flood_list <- list.files(path = "D:/Onedrive/PhD_Undernutrition_Uganda_Physical_Accessbility/2_Study_2_Flooding_Analysis/Data/RAW/Flood_extents_Kampala", pattern = "\\.shp$", full.names = TRUE, recursive = TRUE) %>% 
  lapply(terra::vect)

# Name the flood extents in flood_list based on their subfolder name
flood_extents_names <- list.files(path = "D:/Onedrive/PhD_Undernutrition_Uganda_Physical_Accessbility/2_Study_2_Flooding_Analysis/Data/RAW/Flood_extents_Kampala", pattern = "\\.shp$", full.names = F, recursive = TRUE)

flood_extents_names <- gsub("/.*", "", flood_extents_names)

for (i in 1:length(flood_list)) {
    flood_list[[i]]$Scenario <- gsub("flood_", "", flood_extents_names[i])
}

# Remove other variable names from the flood extents
floods <- lapply(flood_list, function(x) {
    x$rainfall <- NULL
    x$duration <- NULL
    x$threshold <- NULL
    x$fid <- NULL
    return(x)
})

# Load all floods as seperate objects
flood_100_10800 = floods[[1]]
flood_100_21600 = floods[[2]]
flood_100_3600 = floods[[3]]

flood_20_10800 = floods[[4]]
flood_20_21600 = floods[[5]]
flood_20_3600 = floods[[6]]

flood_40_10800 = floods[[7]]
flood_40_21600 = floods[[8]]
flood_40_3600 = floods[[9]]

flood_60_10800 = floods[[10]]
flood_60_21600 = floods[[11]]
flood_60_3600 = floods[[12]]

flood_80_10800 = floods[[13]]
flood_80_21600 = floods[[14]]
flood_80_3600 = floods[[15]]

Flood_extents_full = floods[[16]]

# Create a grid of the plots
## plot for all scenarios
# Create a grid of plots for all 15 scenarios
grid_plot <- cowplot::plot_grid(
  ggplot(flood_20_3600) +
    geom_spatvector(color = "blue", fill = "lightblue") +
    labs(title = "20mm / 1hr") +
    theme_bw() +
    theme(plot.title = element_text(size = 14, face = "bold"),
    axis.title = element_blank(),
    axis.text = element_blank(),
    panel.grid.major = element_blank(),
    panel.grid.minor = element_blank(),
    panel.border = element_blank()),
  
  ggplot(flood_20_10800) +
    geom_spatvector(color = "blue", fill = "lightblue") +
    labs(title = "20mm / 3hr") +
    theme_bw() +
    theme(plot.title = element_text(size = 14, face = "bold"),
    axis.title = element_blank(),
    axis.text = element_blank(),
    panel.grid.major = element_blank(),
    panel.grid.minor = element_blank(),
    panel.border = element_blank()),
  
  ggplot(flood_20_21600) +
    geom_spatvector(color = "blue", fill = "lightblue") +
    labs(title = "20mm / 6hr") +
    theme_bw() +
    theme(plot.title = element_text(size = 14, face = "bold"),
    axis.title = element_blank(),
    axis.text = element_blank(),
    panel.grid.major = element_blank(),
    panel.grid.minor = element_blank(),
    panel.border = element_blank()),
  
  ggplot(flood_40_3600) +
    geom_spatvector(color = "blue", fill = "lightblue") +
    labs(title = "40mm / 1hr") +
    theme_bw() +
    theme(plot.title = element_text(size = 14, face = "bold"),
    axis.title = element_blank(),
    axis.text = element_blank(),
    panel.grid.major = element_blank(),
    panel.grid.minor = element_blank(),
    panel.border = element_blank()),
  
  ggplot(flood_40_10800) +
    geom_spatvector(color = "blue", fill = "lightblue") +
    labs(title = "40mm / 3hr") +
    theme_bw() +
    theme(plot.title = element_text(size = 14, face = "bold"),
    axis.title = element_blank(),
    axis.text = element_blank(),
    panel.grid.major = element_blank(),
    panel.grid.minor = element_blank(),
    panel.border = element_blank()),
  
  ggplot(flood_40_21600) +
    geom_spatvector(color = "blue", fill = "lightblue") +
    labs(title = "40mm / 6hr") +
    theme_bw() +
    theme(plot.title = element_text(size = 14, face = "bold"),
    axis.title = element_blank(),
    axis.text = element_blank(),
    panel.grid.major = element_blank(),
    panel.grid.minor = element_blank(),
    panel.border = element_blank()),
  
  ggplot(flood_60_3600) +
    geom_spatvector(color = "blue", fill = "lightblue") +
    labs(title = "60mm / 1hr") +
    theme_bw() +
    theme(plot.title = element_text(size = 14, face = "bold"),
    axis.title = element_blank(),
    axis.text = element_blank(),
    panel.grid.major = element_blank(),
    panel.grid.minor = element_blank(),
    panel.border = element_blank()),
  
  ggplot(flood_60_10800) +
    geom_spatvector(color = "blue", fill = "lightblue") +
    labs(title = "60mm / 3hr") +
    theme_bw() +
    theme(plot.title = element_text(size = 14, face = "bold"),
    axis.title = element_blank(),
    axis.text = element_blank(),
    panel.grid.major = element_blank(),
    panel.grid.minor = element_blank(),
    panel.border = element_blank()),
  
  ggplot(flood_60_21600) +
    geom_spatvector(color = "blue", fill = "lightblue") +
    labs(title = "60mm / 6hr") +
    theme_bw() +
    theme(plot.title = element_text(size = 14, face = "bold"),
    axis.title = element_blank(),
    axis.text = element_blank(),
    panel.grid.major = element_blank(),
    panel.grid.minor = element_blank(),
    panel.border = element_blank()),
  
  ggplot(flood_80_3600) +
    geom_spatvector(color = "blue", fill = "lightblue") +
    labs(title = "80mm / 1hr") +
    theme_bw() +
    theme(plot.title = element_text(size = 14, face = "bold"),
    axis.title = element_blank(),
    axis.text = element_blank(),
    panel.grid.major = element_blank(),
    panel.grid.minor = element_blank(),
    panel.border = element_blank()),
  
  ggplot(flood_80_10800) +
    geom_spatvector(color = "blue", fill = "lightblue") +
    labs(title = "80mm / 3hr") +
    theme_bw() +
    theme(plot.title = element_text(size = 14, face = "bold"),
    axis.title = element_blank(),
    axis.text = element_blank(),
    panel.grid.major = element_blank(),
    panel.grid.minor = element_blank(),
    panel.border = element_blank()),
  
  ggplot(flood_80_21600) +
    geom_spatvector(color = "blue", fill = "lightblue") +
    labs(title = "80mm / 6hr") +
    theme_bw() +
    theme(plot.title = element_text(size = 14, face = "bold"),
    axis.title = element_blank(),
    axis.text = element_blank(),
    panel.grid.major = element_blank(),
    panel.grid.minor = element_blank(),
    panel.border = element_blank()),
  
  ggplot(flood_100_3600) +
    geom_spatvector(color = "blue", fill = "lightblue") +
    labs(title = "100mm / 1hr") +
    theme_bw() +
    theme(plot.title = element_text(size = 14, face = "bold"),
    axis.title = element_blank(),
    axis.text = element_blank(),
    panel.grid.major = element_blank(),
    panel.grid.minor = element_blank(),
    panel.border = element_blank()),
  
  ggplot(flood_100_10800) +
    geom_spatvector(color = "blue", fill = "lightblue") +
    labs(title = "100mm / 3hr") +
    theme_bw() +
    theme(plot.title = element_text(size = 14, face = "bold"),
    axis.title = element_blank(),
    axis.text = element_blank(),
    panel.grid.major = element_blank(),
    panel.grid.minor = element_blank(),
    panel.border = element_blank()),
  
  ggplot(flood_100_21600) +
    geom_spatvector(color = "blue", fill = "lightblue") +
    labs(title = "100mm / 6hr") +
    theme_bw() +
    theme(plot.title = element_text(size = 14, face = "bold"),
    axis.title = element_blank(),
    axis.text = element_blank(),
    panel.grid.major = element_blank(),
    panel.grid.minor = element_blank(),
    panel.border = element_blank()),
  ncol = 3, nrow = 5
)

# Display the grid of plots
grid_plot

# Save the grid of plots as a PNG
ggsave("D:/Onedrive/PhD_Undernutrition_Uganda_Physical_Accessbility/2_Study_2_Flooding_Analysis/Plots/flood_scenarios.png", grid_plot, width = 20, height = 30, units = "cm", dpi = 600, bg = "white")
```


# Test coverage processing
```{r}
# load the test coverage data
pop_coverage <- read.csv("D:/Onedrive/PhD_Undernutrition_Uganda_Physical_Accessbility/2_Study_2_Flooding_Analysis/AM5_flood_project/out/2024-03-26-14-16-42/MLC_flood_100_10800/zonalStat/zonalStat__MLC_flood_100_10800.csv")

# Cleaning the data
pop_coverage$table.pname2016 = as.factor(pop_coverage$table.pname2016)
pop_coverage$table.time_m = as.factor(pop_coverage$table.time_m)

# Remove the 'empty' column from the pop_coverage data frame
pop_coverage <- subset(pop_coverage, select = -empty)

# GGplot
ggplot(pop_coverage, aes(x = table.time_m, y = table.popCoveredPercent, fill = table.popCoveredPercent)) +
  geom_bar(stat = "identity") +
  labs(title = "Population Coverage by Time", x = "Time (minutes)", y = "Population Covered (%)") +
  theme_bw() +
  theme(plot.title = element_text(size = 14, face = "bold"),
    axis.title = element_text(size = 12),
    axis.text = element_text(size = 10),
    panel.grid.major = element_blank(),
    panel.grid.minor = element_blank(),
    panel.border = element_blank(),
    legend.position = "none") + 
  facet_wrap(~ table.pname2016) +
  scale_fill_gradient(low = "red", high = "light green") +
  theme(plot.margin = margin(1, 1, 1, 1, "cm")) + 
  theme(plot.background = element_rect(fill = "white"))



```