################################################################
# TRAVEL TIME EXTRACTION
################################################################


################################################################
# Initialize and Load packages
################################################################

################################################################
# This code was provided by Oumar Ba and is used to account for the DHS displacement in the travel time extraction
################################################################

# Packages
# devtools::install_github("ropensci/rdhs")
library(sf)
library(tidyverse)
library(dplyr)
library(lubridate)
library(furrr)
library(labelled)
library(flextable)
library(stargazer)
library("rnaturalearth")
library("rnaturalearthdata")
library(table1)
library(fixest)
library(lmtest)
library(texreg)
library("raster")
library(broom)
library(terra)
library(viridis)
library(scales) # for the labels
library(exactextractr) # for exact_extract command
library(readxl)
library(archive)
library(naniar) # for command replace_with_na




# To DO
# # Cut part of the buffer that fall over water => This value are NA and with exact_extract, NA values area automatically dropped
# # Cut the buffer to consider only within country => ??


################################################################
# Set the correct buffer for zonal stat of rural and urban areas (for weightening)
################################################################

# Transform the database in spatvector  and
# final_data <- readRDS(file = "data/processed/final_data/final_data.Rds")
extract_table_bf_rr_ub <- final_data %>%
  as.data.frame() %>%
  dplyr::select(LONGNUM, LATNUM, place_of_residence, CountryName) %>% #  here is the id generated by the chirps command
  distinct(LONGNUM, LATNUM, place_of_residence, .keep_all = TRUE) %>% # I drop duplicate respondent within the same DHS cluster to speed computation time.
  mutate(place_of_residence = to_character(place_of_residence)) %>% # Convert "place_of_residence"  value into its attached characters
  vect(geom = c("LONGNUM", "LATNUM"), crs = "+proj=longlat +datum=WGS84 +no_defs", keepgeom = TRUE)

# Split the SpatVector based on place_of_residence
urban_points <- extract_table_bf_rr_ub[extract_table_bf_rr_ub$place_of_residence == "urban", ]
rural_points <- extract_table_bf_rr_ub[extract_table_bf_rr_ub$place_of_residence == "rural", ]

# Create buffers for urban and rural points
urban_buffers <- lapply(1:nrow(urban_points), function(i) buffer(urban_points[i, ], width = 2000))
rural_buffers <- lapply(1:nrow(rural_points), function(i) buffer(rural_points[i, ], width = 5000))

# Combine all buffers
all_buffers <- c(urban_buffers, rural_buffers)

# Convert list of SpatVectors to a single SpatVector
extract_table_bf_rr_ub <- do.call(rbind, all_buffers)

# Save in shp for verification in QGIS
terra::writeVector(extract_table_bf_rr_ub, " data/temp/extract_table_bf_rr_ub.shp", overwrite = TRUE)


################################################################
# Create some functions for the extraction of TT summary statistics
################################################################


# Function to compute TT weighted mean and other summary statistics from a single country-polygon (with correction for unpopulated cells)
compute_weighted_mean <- function(polygon, travel_time_raster, pop_raster) {
  # Extract the weights (population values) for the current polygon
  weights_values <- exact_extract(pop_raster, polygon)

  # If all weights are NA for this polygon, create a temporary raster with values set to 1
  if (all(is.na(weights_values[[1]]$value))) {
    tmp_raster <- pop_raster
    tmp_raster[] <- 1
    weights_raster <- tmp_raster
  } else {
    weights_raster <- pop_raster
  }

  # Compute the weighted mean using the chosen weights raster
  result <- exact_extract(travel_time_raster, polygon,
    # A) For weight with population raster use like : "exact_extract(rast, poly, 'weighted_mean', weights=weights)" )
    # B)In all of the summary operations, NA values in the the primary raster (x) raster are ignored (i.e., na.rm = TRUE.) If NA values occur
    # in the weighting raster, the result of the weighted operation will be NA. NA values in both x and weights can be replaced on-the-fly using
    # the default_value and default_weight arguments.
    fun = c("mean", "min", "max", "mode", "median", "sum", "mean", "weighted_mean"),
    weights = weights_raster,
    default_weight = 0,
    append_cols = c("LONGNUM", "LATNUM", "place_of_residence", "CountryName"),
    progress = TRUE
  )

  return(result)
}

# Function that run compute_weighted_mean function across all country-polygons from a same country and append results
extract_travel_time <- function(country_name, travel_time_raster, pop_raster, extract_table) {
  # Check CRS before reprojection
  print("Check CRS before reprojection")
  print(extract_table)
  print(travel_time_raster)
  print(pop_raster)

  # Filter for DHS in the specified country and reproject to the travel time raster CRS
  extract_table_pr <- extract_table[extract_table$CountryName == country_name, ] # The bug is here "Sierra Leone" is not detected
  extract_table_pr <- project(extract_table_pr, travel_time_raster) # Can be improve condition that stop script if crs of extract_table_pr, travel_time_raster and pop_raster are different

  # Check CRS after reprojection
  print("Check CRS after reprojection")
  print(extract_table_pr)
  print(travel_time_raster)
  print(pop_raster)

  # Convert into sf, sfc, SpatialPolygonsDataFrame, or SpatialPolygons as exact_extract want this format
  extract_table_pr_sf <- st_as_sf(extract_table_pr)

  # Loop through each row (i.e., each polygon) in extract_table_pr_sf to compute summary stat and TT pop weighted mean
  results <- lapply(1:nrow(extract_table_pr_sf), function(i) {
    compute_weighted_mean(extract_table_pr_sf[i, ], travel_time_raster, pop_raster)
  })

  # Bind results together
  extract_result <- bind_rows(results)


  return(extract_result)
}

# Function to compute TT pop weighted median (with correction for unpopulated cells)
TT_pop_weighted_median <-
  function(polygon, travel_time_raster, pop_raster) {
    result_median <- exact_extract(
      travel_time_raster,
      polygon,
      fun = function(values, coverage_frac, weights) {
        # If all weights are zero, assume each weight is 1
        # Because with  default_weight = 0,  when there is no population at all in the buffer, it take the smallest TT pixel value in the buffer because we ordered the value before and cum_weighted_coverage_frac never increases and
        # is always equals to 0. Therefore, the first element of cum_weighted_coverage_frac is >= to total_weighted_coverage_frac as 0>=0 is TRUE.  We want to avoid that
        if (all(weights == 0)) {
          weights <- rep(1, length(values))
        }

        # Ensure the data is ordered by the values
        ord <-
          order(values, na.last = NA) # na.last is set by default to TRUE and in this case, missing values in the data are put last. This biased the median when we have population that fall in water with NA in TT. Therefore  I set na.last = NA which remove missing values
        values <- values[ord]
        weighted_coverage_frac <- coverage_frac * weights
        weighted_coverage_frac <- weighted_coverage_frac[ord]

        # Compute the cumulative sum of weighted_coverage_frac
        cum_weighted_coverage_frac <- cumsum(weighted_coverage_frac)
        total_weighted_coverage_frac <- sum(weighted_coverage_frac)

        # Find where the cumulative weight surpasses half of the total weight (show row numbers where we are over 0.5 of the total weight and select the first row number)
        idx <-
          which(cum_weighted_coverage_frac >= total_weighted_coverage_frac / 2)[1]

        # Return the weighted median
        return(values[idx])
      },
      weights = pop_raster,
      # When default_weight = 0 is not set, anytime there is at least one NA in the pop raster within the buffer, the median TT will be NA
      default_weight = 0,
      append_cols = c("LONGNUM", "LATNUM", "place_of_residence", "CountryName")
    )

    return(result_median)
  }


# Function that run TT_pop_weighted_median function across all country-polygons from a same country and append results
extract_travel_time_median <- function(country_name, travel_time_raster, pop_raster, extract_table) {
  # Check CRS before reprojection
  print("Check CRS before reprojection")
  print(extract_table)
  print(travel_time_raster)
  print(pop_raster)

  # Filter for DHS in the specified country and reproject to the travel time raster CRS
  extract_table_pr <- extract_table[extract_table$CountryName == country_name, ] # The bug is here "Sierra Leone" is not detected
  extract_table_pr <- project(extract_table_pr, travel_time_raster) # Can be improve condition that stop script if crs of extract_table_pr, travel_time_raster and pop_raster are different

  # Check CRS after reprojection
  print("Check CRS after reprojection")
  print(extract_table_pr)
  print(travel_time_raster)
  print(pop_raster)

  # Convert into sf, sfc, SpatialPolygonsDataFrame, or SpatialPolygons as exact_extract want this format
  extract_table_pr_sf <- st_as_sf(extract_table_pr)

  # Loop through each row (i.e., each polygon) in extract_table_pr_sf to compute summary stat and TT pop weighted mean
  results_median <- lapply(1:nrow(extract_table_pr_sf), function(i) {
    TT_pop_weighted_median(extract_table_pr_sf[i, ], travel_time_raster, pop_raster)
  })

  # Bind results together
  extract_result_median <- bind_rows(results_median)

  return(extract_result_median)
}



################################################################
# Create extraction table to loop over
################################################################

# Create extraction table listing Country code, Country name, epsg_code, Travel time files names and population raster files names
# Download and list of country name and their projection
download.file("https://github.com/fleurhierink/Population_Access/raw/main/data/raw/projections/projections.xlsx", "data/processed/Travel_times_projection_list/projections.xlsx")
projections <- read_excel("data/processed/Travel_times_projection_list/projections.xlsx")

# Filter for relevant countries that in the DHS
country_list <- sort(unique(extract_table_bf_rr_ub$CountryName))

# Create a table with the relevant countries along with their country code and epsg_code
country_table <- projections %>%
  filter(country %in% country_list | country_code %in% c("SLE", "ZAF")) #  # South Africa and Sierra Leone dont match when I use merge because they are composed of two words

# Attach the country name to the corresponding travel raster
travel_time_files <- list.files("data/processed/rTravel_times/") %>%
  as.data.frame() %>%
  rename(travel_time_files = ".") %>%
  mutate(country_code = str_replace_all(travel_time_files, c("travel_time_" = "", ".tif" = ""))) # I get the raster file names  and country code until here

# Attach the country name to the corresponding population raster
pop_raster_files <- pop_raster_files <- list.files("data/raw/worldpop/worldpop_constrained/") %>%
  as.data.frame() %>%
  rename(pop_raster_files = ".") %>%
  mutate(country_code = str_replace_all(pop_raster_files, c("rPopulation_" = "", ".tif" = ""))) # I get the raster file names  and country code until here

# Merge travel time raster, pop raster and table with relevant countries along their country code and epsg_code
travel_time_pop_epsg_files <- country_table %>%
  left_join(travel_time_files, by = "country_code") %>% #  I merge the latter with country names
  left_join(pop_raster_files, by = "country_code") %>%
  sort("country")

# Attach the country name from country_list because Sierra Lenoe and South Africa are filtered properly only in the object
travel_time_pop_epsg_files <- cbind(travel_time_pop_epsg_files, country_list)



################################################################
# Sequential extraction process using a loop over the extraction table
################################################################

# Initialize an empty list to store the results
travel_time_extr_list <- list()
travel_time_extr_median_list <- list()


# Loop over the extract table that record travel time and pop raster file paths and corresponding country names
for (i in 1:nrow(travel_time_pop_epsg_files)) {
  # Set file names to read
  travel_time_file_name <- travel_time_pop_epsg_files$travel_time_files[i]
  pop_raster_file_name <- travel_time_pop_epsg_files$pop_raster_files[i]
  country_name <- travel_time_pop_epsg_files$country_list[i]

  # Import travel time raster
  travel_time_raster <- rast(paste0("data/processed/rTravel_times/", travel_time_file_name))

  # Import population raster
  pop_raster <- rast(paste0("data/raw/worldpop/worldpop_constrained/", pop_raster_file_name))

  # Extract travel time statistics for the current country
  extract_result <- extract_travel_time(country_name, travel_time_raster, pop_raster, extract_table_bf_rr_ub) # With this function the travel time computed for  the country is only used => question to fleur => some pixel crosss national border
  # Append the result to its respective list
  travel_time_extr_list[[i]] <- extract_result

  # Extract weighted median travel time for the current country
  extract_result_median <- extract_travel_time_median(country_name, travel_time_raster, pop_raster, extract_table_bf_rr_ub)
  # Append the result to its respective list
  travel_time_extr_median_list[[i]] <- extract_result_median

  # Remove travel time and population raster
  rm(travel_time_raster, pop_raster)
}


# Append travel time results of all countries in one table and rename variable
travel_time_extr <- do.call(rbind, travel_time_extr_list) %>%
  rename(
    travel_time_mean = mean,
    travel_time_min = min,
    travel_time_max = max,
    travel_time_mode = mode,
    travel_time_sum = sum,
    travel_time_median = median,
    travel_time_weighted_mean = weighted_mean
  ) %>%
  dplyr::select(-c(place_of_residence, CountryName)) # these variable are already present in my final data

# Append weighted median travel time results of all countries in one table and rename variable
travel_time_extr_median <- do.call(rbind, travel_time_extr_median_list) %>%
  rename(travel_time_weighted_median = result) %>%
  dplyr::select(-c(place_of_residence, CountryName)) # these variable are already present in my final data


################################################################
# Merge and check results
################################################################


# Merge all travel time results
travel_time_extr_final <- travel_time_extr %>%
  left_join(travel_time_extr_median, by = c("LATNUM", "LONGNUM"))


# Merge to final data
final_data <- final_data %>%
  left_join(travel_time_extr_final, by = c("LATNUM", "LONGNUM")) # check if I can improve it



# Check respondent with missing travel time
summary(final_data$travel_time_mean)
final_data %>%
  dplyr::select(LONGNUM, LATNUM, place_of_residence, CountryName, resp_id, travel_time_mean, travel_time_mode, travel_time_median) %>%
  filter(is.na(travel_time_mean)) %>%
  View()

# All respondent with NA travel time live close to water and most of them in small island
dhs_missing_travel_time_data <- final_data %>%
  st_as_sf(
    coords = c("LONGNUM", "LATNUM"), crs = "+proj=longlat +datum=WGS84 +no_defs",
    remove = FALSE,
    na.fail = F
  ) %>%
  dplyr::select(resp_id, travel_time_mean) %>%
  filter(is.na(travel_time_mean)) %>%
  st_write("data/temp/dhs_missing_travel_time_data.shp", append = F)




################################################################
# Save the final data
################################################################

# Save the dataset (rds format)
saveRDS(final_data, file = "data/processed/final_data/final_data.Rds") # final_data <- readRDS(file = "data/processed/final_data/final_data.Rds")


################################################################
# Create a temporary shapefile of the final data to check TT results in QGIS
################################################################


# Save the dataset in lighter format (shp format)
final_data %>%
  st_as_sf(
    coords = c("LONGNUM", "LATNUM"), crs = "+proj=longlat +datum=WGS84 +no_defs",
    remove = FALSE,
    na.fail = F
  ) %>%
  dplyr::select(resp_id, birth_date, travel_time_median) %>%
  st_write("data/temp/final_data_lighter_travel_time.shp", append = F)
